#!/usr/bin/env bash

REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/codex-dotfiles"

codex_home_dir() {
  printf '%s\n' "${CODEX_HOME:-$HOME/.codex}"
}

host_os() {
  uname -s 2>/dev/null || printf 'unknown\n'
}

is_windows_host() {
  case "$(host_os)" in
    MINGW*|MSYS*|CYGWIN*)
      return 0
      ;;
  esac

  return 1
}

die() {
  echo "$*" >&2
  exit 1
}

ensure_command() {
  command -v "$1" >/dev/null 2>&1 || die "$1 not found"
}

git_repo() {
  git -C "$REPO_DIR" "$@"
}

ensure_git_repo() {
  git_repo rev-parse --show-toplevel >/dev/null 2>&1 || die "Not a git repo: $REPO_DIR"
}

current_branch() {
  git_repo symbolic-ref --quiet --short HEAD 2>/dev/null || true
}

push_current_branch() {
  local branch
  branch=$(current_branch)

  [ -n "$branch" ] || die "Cannot push from detached HEAD."

  if git_repo rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' >/dev/null 2>&1; then
    git_repo push
    return 0
  fi

  git_repo remote get-url origin >/dev/null 2>&1 || die "No origin remote configured."
  git_repo push -u origin "$branch"
}

timestamp() {
  date '+%Y-%m-%d %H:%M:%S%:z'
}

write_default_local_config() {
  local codex_home

  codex_home=$(codex_home_dir)

  cat <<EOF
# Machine-local Codex config archive.
# Refreshed from $codex_home/config.toml before install or sync.
# Keep this file out of Git.
#
# Example:
# [projects."/absolute/path"]
# trust_level = "trusted"
EOF
}

path_is_excluded() {
  local rel="$1"
  shift
  local pattern trimmed

  for pattern in "$@"; do
    [ -n "$pattern" ] || continue

    case "$pattern" in
      */)
        trimmed=${pattern%/}
        case "$rel" in
          "$trimmed"|"$trimmed"/*|*/"$trimmed"|*/"$trimmed"/*)
            return 0
            ;;
        esac
        ;;
      *)
        case "$rel" in
          $pattern)
            return 0
            ;;
        esac
        ;;
    esac
  done

  return 1
}

copy_tree_contents() {
  local src_dir="$1"
  local dst_dir="$2"
  shift 2
  local path rel target path_type

  rm -rf "$dst_dir"
  mkdir -p "$dst_dir"

  while IFS= read -r -d '' path; do
    rel=${path#"$src_dir"/}

    if [ -L "$path" ]; then
      echo "Skipping symlink source: $path"
      continue
    fi

    if [ -d "$path" ]; then
      path_type="dir"
    else
      path_type="file"
    fi

    if path_is_excluded "$rel" "$@"; then
      continue
    fi

    target="$dst_dir/$rel"

    if [ "$path_type" = "dir" ]; then
      mkdir -p "$target"
      continue
    fi

    mkdir -p "$(dirname "$target")"
    cp -fP "$path" "$target"
  done < <(find -P "$src_dir" -mindepth 1 -print0)
}

ensure_local_config_file() {
  local dst="$1"

  [ -f "$dst" ] && return 0

  mkdir -p "$(dirname "$dst")"
  write_default_local_config > "$dst"
}

sanitize_shared_config() {
  local src="$1"
  local dst="$2"

  awk '
    BEGIN {
      skip_projects = 0
      stop_local = 0
    }
    /^# Generated by codex-dotfiles\// {next}
    /^# Edit codex\/config.shared.toml for shared settings\./ {next}
    /^# For machine-local settings, edit the local block in .*\/config.toml\./ {next}
    /^# Machine-local overrides$/ {
      stop_local = 1
      next
    }
    stop_local {next}
    /^\[projects\."/ {
      skip_projects = 1
      next
    }
    skip_projects && /^\[/ {
      skip_projects = 0
    }
    skip_projects {next}
    {print}
  ' "$src" > "$dst"
}

extract_local_config() {
  local src="$1"
  local dst="$2"
  local mode="${3:-if-missing}"
  local codex_home
  local tmp
  local has_local_marker=0

  [ -f "$src" ] || return 1

  codex_home=$(codex_home_dir)
  tmp=$(mktemp)

  if grep -q '^# Machine-local overrides$' "$src"; then
    has_local_marker=1
  fi

  awk -v config_path="$codex_home/config.toml" -v has_local_marker="$has_local_marker" '
    BEGIN {
      capture = has_local_marker ? 0 : 1
      in_projects = 0
      printed_header = 0
    }
    function print_header() {
      if (!printed_header) {
        print "# Machine-local Codex config archive."
        print "# Refreshed from " config_path " before install or sync."
        print "# Keep this file out of Git."
        print ""
        printed_header = 1
      }
    }
    /^# Machine-local overrides$/ {
      if (has_local_marker) {
        capture = 1
        next
      }
    }
    !capture {next}
    /^\[projects\."/ {
      in_projects = 1
      print_header()
      print
      next
    }
    in_projects && /^\[/ {
      in_projects = 0
    }
    in_projects {print}
  ' "$src" > "$tmp"

  if [ ! -s "$tmp" ]; then
    rm -f "$tmp"
    return 1
  fi

  if [ "$mode" = "if-missing" ] && [ -f "$dst" ]; then
    rm -f "$tmp"
    return 0
  fi

  mkdir -p "$(dirname "$dst")"

  if [ -f "$dst" ] && cmp -s "$tmp" "$dst"; then
    rm -f "$tmp"
    return 0
  fi

  mv "$tmp" "$dst"
}

lock_file_for() {
  local name="$1"
  local repo_hash

  repo_hash=$(printf '%s\n' "$REPO_DIR" | cksum | awk '{print $1}')
  printf '%s/codex-dotfiles-%s.%s.lock\n' "${XDG_RUNTIME_DIR:-$STATE_DIR}" "$name" "$repo_hash"
}

repo_state_file() {
  local name="$1"
  local repo_hash

  repo_hash=$(printf '%s\n' "$REPO_DIR" | cksum | awk '{print $1}')
  printf '%s/%s.%s\n' "$STATE_DIR" "$name" "$repo_hash"
}

log_to() {
  local log_file="$1"
  shift
  local ts

  mkdir -p "$(dirname "$log_file")"
  ts=$(date '+%Y-%m-%d %H:%M:%S')
  echo "[$ts] $*" | tee -a "$log_file"
}

acquire_lock() {
  local lock_file="$1"

  if ! command -v flock >/dev/null 2>&1; then
    return 0
  fi

  mkdir -p "$(dirname "$lock_file")"

  exec {LOCK_FD}> "$lock_file"
  flock -n "$LOCK_FD" && return 0

  exec {LOCK_FD}>&-
  unset LOCK_FD
  return 1
}
