#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$SCRIPT_DIR/common.sh"
SOURCE_DIR="$REPO_DIR/codex"
TARGET_DIR=$(codex_home_dir)
SHARED_CONFIG="$SOURCE_DIR/config.shared.toml"
LOCAL_CONFIG="$TARGET_DIR/config.local.toml"
TARGET_CONFIG="$TARGET_DIR/config.toml"

mkdir -p "$TARGET_DIR"

[ -f "$SHARED_CONFIG" ] || die "Missing $SHARED_CONFIG. Run ./codexctl init first, or create codex/config.shared.toml."

if [ -f "$TARGET_CONFIG" ]; then
  extract_local_config "$TARGET_CONFIG" "$LOCAL_CONFIG" overwrite || true
fi

ensure_local_config_file "$LOCAL_CONFIG"

tmp_file=$(mktemp)
trap 'rm -f "$tmp_file"' EXIT

{
  echo "# Generated by codex-dotfiles/bootstrap/render-config.sh"
  echo "# Edit codex/config.shared.toml for shared settings."
  echo "# For machine-local settings, edit the local block in $TARGET_CONFIG."
  echo
  cat "$SHARED_CONFIG"
  if [ -s "$LOCAL_CONFIG" ]; then
    echo
    echo "# Machine-local overrides"
    cat "$LOCAL_CONFIG"
  fi
} > "$tmp_file"

mv "$tmp_file" "$TARGET_CONFIG"
